pub mod coordinator;
pub mod worker;

/// FileDescriptorSet for gRPC reflection (generated by build.rs).
/// Used by `ingestion_engine::application::coordinator` to enable
/// `grpcurl` / `grpcui` without extra .proto distribution.
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!("file_descriptor_set.bin");
